### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by mattrayner** [waringer/broadlink#2]
Hi @waringer,
 I'm trying to use the send command-line option using the code learned from `-learn`, and I'm getting a decoding error that it's not clear how to fix.

```bash
go run main.go -ip=192.168.1.84 -v -d -learned
Broadlink RM Toolbox
[01] Device type: 272A 
[01] Device name: 智能遥控 
[01] Device MAC: [ ** ** ** ** ** ** ] 
[01] Device IP: 192.168.1.84 
[01] Device authenticated 
Found 1 device(s)
[00] Device last learned code: [26004800471918191719182e172f171818181718182f1819172f1719172f1718182e172e18000cf54719171918191630162f1719171916191730171a1630161a162f1719172f16] 
```

```bash
go run main.go -ip=192.168.1.84 -v -d -send [26004800481917191818182e182e171917181818171a18191719171917191719172e181817000cc3481917191819172f172e181818181718181a1719171918181]
Broadlink RM Toolbox
[01] Device type: 272A 
[01] Device name: 智能遥控 
[01] Device MAC: [ ** ** ** ** ** ** ] 
[01] Device IP: 192.168.1.84 
[01] Device authenticated 
Found 1 device(s)
2020/05/18 18:34:34 Provided Broadlink IR code is invalid
exit status 1
```

I've also tried wrapping the code in single and double quotes with the same problem, am I just missing something stupid?

Thanks,
Matt

**Comment by mattrayner** [comment]
Additionally, after running this command multiple times I get the un-adding error:

```bash
goroutine 1 [running]:
github.com/mattrayner/broadlink/broadlinkrm.unPadding(...)
        /Users/matthewrayner/go/src/github.com/mattrayner/broadlink/broadlinkrm/broadlinkrm.go:310
github.com/mattrayner/broadlink/broadlinkrm.decrypt(0xc0000960c4, 0x10, 0x1c, 0x1265880, 0x10, 0x10, 0xc0000ac128, 0x10, 0x10, 0xc000059cf8, ...)
        /Users/matthewrayner/go/src/github.com/mattrayner/broadlink/broadlinkrm/broadlinkrm.go:300 +0x211
github.com/mattrayner/broadlink/broadlinkrm.Command(0xc000000002, 0xc0000b6000, 0x47, 0x90, 0xc000059d88, 0xc0000b6000, 0xc000059d80, 0x104cbfb)
        /Users/matthewrayner/go/src/github.com/mattrayner/broadlink/broadlinkrm/broadlinkrm.go:163 +0x1c5
main.send(0xc0000b6000, 0x47, 0x90, 0xc0000a6140, 0x1, 0x1)
        /Users/matthewrayner/go/src/github.com/mattrayner/broadlink/main.go:223 +0x141
main.main()
        /Users/matthewrayner/go/src/github.com/mattrayner/broadlink/main.go:63 +0x423
exit status 2

```

**Comment by waringer** [comment]
Hello @mattrayner,

i have looked into your first post and, please send the learnd code without the squared brackets. 

```
go run main.go -ip=192.168.1.84 -v -d -send 26004800471918191719182e172f171818181718182f1819172f1719172f1718182e172e18000cf54719171918191630162f1719171916191730171a1630161a162f1719172f16
```

Then i have noticed that the code you send is not the one you have from the learning. The code is written in hex and because of this it have be an even number of digits. But the code you try to send have an odd number an can't be parsed.

I hope this solves you first problem, i look into you second post now ;)

**Comment by waringer** [comment]
Hello again,

about your second post, i can't say much. It look like the cryptographic message is corrupted and can't be decoded. I can only guess why that is, perhaps the wireless network had a hiccup and lost some bytes. Broadlink uses the UDP protocol to transfer data and UDP don't have error detection or correction, so this can happen :(

I will look deeper into this tomorrow and try to fix this.

**Comment by mattrayner** [comment]
Thanks for your prompt reply, it seems once I get the errors on the second post the only way to 'fix' it is to reboot the device

**Comment by waringer** [comment]
About the second post, i have tryed to reproduce it with my device but had no luck. I have now patched the code to prevent to panic in this special case and point with the panic message you provided and hope this will help.

**Comment by mattrayner** [comment]
Hi @waringer thanks again for the prompt response and reply, that has worked perfectly! Thanks for providing this well written and useful library 😄
